baseURL = 'http://example.org/'
languageCode = 'es-mx'
title = 'Tecnomanía'
theme = "dream"
defaultContentLanguage = "es"
[params]
lightTheme = "emerald"
darkTheme = "forest"
avatar = "/uploads/logo_tecnomania.png"
favicon = "/favicon.ico"
headerTitle = "Tecnomanía"

[params.navItems]
facebook = { href = "https://www.facebook.com/TecnomaniaMXN", target="_blank", icon = "logo-facebook", title = "Facebook" }
instagram = { href = "https://www.instagram.com/tecnomania_store", target="_blank", icon = "logo-instagram", title = "Instagram" }