baseURL = 'http://example.org/'
languageCode = 'es-mx'
title = 'Tecnomanía'
theme = "dream"
defaultContentLanguage = "es"

[params]
lightTheme = "emerald"
darkTheme = "forest"
avatar = "/uploads/logo_tecnomania.png"
favicon = "/favicon.ico"
headerTitle = "Tecnomanía"
showSummaryCoverInPost = true
motto = "Tu tienda de tecnología"
reorderNavItems = ["search", "rss", "posts", "categories", "tags", "contacto", "facebook", "instagram", "admin"]

[params.navItems]
facebook = { href = "https://www.facebook.com/TecnomaniaMXN", target="_blank", icon = "logo-facebook", title = "Facebook" }
instagram = { href = "https://www.instagram.com/tecnomania_store", target="_blank", icon = "logo-instagram", title = "Instagram" }
admin = { href = "/admin", target="_blank", title = "Ingresar" }
